config/routes.rb
Sprechen::Application.routes.draw do

  get '/auth/:provider/callback' => "sessions#create"

  get '/sign_out' => "sessions#destroy", :as => 'sign_out'

  resources :topics

  resources :conferences do
    collection do
      resources :search, :only => [:new, :create, :show], :controller => "search"
    end
  end

  namespace :speaker, :path => 'speaker/:user/' do
    resource :calendar
    resource :dashboard
    resources :bios
    resources :talks
  end

  root :to => 'home#index'

end

app/models/bio.rb
class Bio

  include Mongoid::Document
  include Mongoid::Timestamps

  field :label
  field :content
  field :photo

  belongs_to :user
  belongs_to :proposal

end

app/models/speaker/bio.rb
class Speaker::Bio

  include Mongoid::Document
  include Mongoid::Timestamps

  field :label
  field :content
  field :photo

  belongs_to :user
  belongs_to :proposal, :class_name => 'Talk::Proposal'

end

app/models/speaker/calendar.rb
class Speaker::Calendar

  attr_accessor :subscriber

  def initialize(subscriber)
    self.subscriber = subscriber
  end

  def conferences
    subscriber.conferences.asc(:start_date)
  end

end

app/models/speaker/dashboard.rb
class Speaker::Dashboard

  attr_accessor :user_id

  def initialize(args={})
    self.user_id = args[:user_id]
  end

  def accepted_talks
    user.proposals.accepted
  end

  def submitted_talks
    user.proposals.awaiting_approval
  end

  def upcoming_conferences
    user.conferences.todo
  end

  def user
    @user ||= User.find(self.user_id)
  end

end

app/controllers/speaker/bios_controller.rb
class Speaker::BiosController < ApplicationController

  include ScopesAndPersistsModel

  before_filter :ensure_current_user
  scopes_and_persists :bio, :class_name => 'Speaker::Bio'

  def index
    @bios = current_user.bios.all
  end

  def new
    @bio = current_user.bios.new
  end

  def edit
  end

  def show
  end

  def destroy
    @bio.destroy && redirect_to(speaker_bios_path(current_user.slug))
  end

  def create
    @bio = current_user.bios.new
    handle_errors_on(:new) || redirect_to(speaker_bios_path(current_user.slug))
  end

  def update
    handle_errors_on(:edit) || redirect_to(speaker_bios_path(current_user.slug))
  end

end

app/controllers/speaker/calendars_controller.rb
class Speaker::CalendarsController < ApplicationController

  before_filter :ensure_current_user

  def show
    redirect_to root_path unless session[:user_id]
    @calendar = Speaker::Calendar.new(current_user)
  end

end

app/controllers/speaker/dashboards_controller.rb
class Speaker::DashboardsController < ApplicationController

  before_filter :ensure_current_user

  def show
    redirect_to root_path unless session[:user_id]
    @dashboard = Speaker::Dashboard.new(:user_id => current_user.id)
  end

end

app/controllers/speaker/talks_controller.rb
class Speaker::TalksController < ApplicationController

  include ScopesAndPersistsModel

  scopes_and_persists :talk, :class_name => "Talk::Talk"

  before_filter :ensure_current_user
  before_filter :scope_abstract, :only => [:new, :edit, :create, :update]

  def index
    @talks = current_user.talks.desc(:created_at)
  end

  def new
    @talk = current_user.talks.new
  end

  def edit
  end

  def show
  end

  def destroy
    @talk.destroy && redirect_to(speaker_talks_path(current_user.slug))
  end

  def create
    @talk = current_user.talks.new
    handle_errors_on(:new)
    @abstract.save! if @abstract.summary.present?
    redirect_to(speaker_talks_path(current_user.slug))
  end

  def update
    handle_errors_on(:edit)
    @abstract.update_attributes(params[:talk_abstract])
    redirect_to(speaker_talks_path(current_user.slug))
  end

  private

  def scope_abstract
    @abstract = @talk.abstracts.first
    @abstract ||= params[:talk_abstract].present? && params[:talk_abstract][:id].present? && @talk.abstracts.where(params[:talk_abstract][:id]).first
    @abstract ||= @talk.abstracts.build(params[:talk_abstract])
  end

end

app/views/speaker/bios/_form.html.haml
.well.form
  = f.hidden_field :user_id, :value => current_user.id
  .span3
    = f.label :label
    = f.text_field :label
    = f.label :photo, "Photo URL"
    = f.text_field :photo
  .span4
    = f.label :content
    = f.text_area :content, :style => 'width: 100%; height: 16em;'
  - if @bio.photo.present?
    .span3.pull-right
      %label Photo
      = image_tag @bio.photo, :style => 'width: 90%;', :class => 'framed'

  %br.clear
= f.submit "Save", :class => 'btn btn-primary'
= link_to "Cancel", :back, :class => 'btn'

- if @bio.persisted?
  .pull-right
    = link_to speaker_bio_path(current_user.slug, @bio), :method => :delete, :class => 'btn btn-danger', :confirm => 'Are you sure?' do
      %i.icon-trash

app/views/speaker/bios/edit.html.haml
= content_for(:title, "Edit a Bio")

= form_for(@bio, :url => speaker_bio_path(current_user.slug, @bio)) do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/speaker/bios/index.html.haml
= content_for(:title, "Your Bios")

- if current_user.bios.count < 2

  .row-fluid
    .span12
      .bubble.closable
        .pull-right.minus-top-margin
          %a.close
            &times;
        %h2
          Introducing You.
        %p
          If you had to describe yourself in 200 words or less, what would you say? Well, that obviously depends on who you're talking to-- that's why we're set up to let you create as many bios as you want to. When it comes time to submit your talk proposal, you can pick the bio that best suits the occasion.
        .left_speech

.row-fluid{:style => "margin-top: 1em;"}
  %section
    - @bios.each do |bio|
      %div.talk.mix.span4.well.medium.single_spaced
        = formatted_bio(bio)
        .controls.reveal-on-mouseover
          = link_to speaker_bio_path(current_user.slug, bio), :class => 'btn btn-mini' do
            %i.icon-eye-open
          = link_to edit_speaker_bio_path(current_user.slug, bio), :class => 'btn btn-mini' do
            %i.icon-edit

%br.clear
%a.btn.btn-inverse{:href => "#{new_speaker_bio_path(current_user.slug)}"}
  %i.icon-user
    %sup +
  Add a Bio

app/views/speaker/bios/new.html.haml
= content_for(:title, "Add a Bio")

= form_for(@bio, :url => speaker_bios_path(current_user.slug)) do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/speaker/bios/show.html.haml
= content_for(:title, "Your Bios: #{@bio.label}")

.row-fluid
  .span9.well
    = @bio.content
  .span3.pull-right
    - if @bio.photo.present?
      = image_tag @bio.photo, :style => 'width: 90%; margin-left: 1em;', :class => 'framed'

%br.clear

= link_to edit_speaker_bio_path(current_user.slug, @bio), :class => 'btn btn-danger' do
  %i.icon-edit
  Edit

= link_to speaker_bios_path(current_user.slug), :class => 'btn btn-danger' do
  Back

.pull-right
  = link_to speaker_bio_path(current_user.slug, @bio), :method => :delete, :class => 'btn btn-danger', :confirm => 'Are you sure?' do
    %i.icon-trash