config/routes.rb
Sprechen::Application.routes.draw do

  get '/auth/:provider/callback' => "sessions#create"

  get '/sign_out' => "sessions#destroy", :as => 'sign_out'

  resources :topics

  resources :conferences do
    collection do
      resources :search, :only => [:new, :create, :show], :controller => "search"
    end
  end

  namespace :speaker, :path => 'speaker/:user/' do
    resource :calendar
    resource :dashboard
    resources :bios
    resources :talks
  end

  root :to => 'home#index'

end

app/models/speaker/bio.rb
class Speaker::Bio

  include Mongoid::Document
  include Mongoid::Timestamps

  field :label
  field :content
  field :photo

  belongs_to :user
  belongs_to :proposal, :class_name => 'Talk::Proposal'

end

app/models/speaker/calendar.rb
class Speaker::Calendar

  attr_accessor :subscriber

  def initialize(subscriber)
    self.subscriber = subscriber
  end

  def conferences
    subscriber.conferences.asc(:start_date)
  end

end

app/models/speaker/dashboard.rb
class Speaker::Dashboard

  attr_accessor :user_id

  def initialize(args={})
    self.user_id = args[:user_id]
  end

  def accepted_talks
    user.proposals.accepted
  end

  def submitted_talks
    user.proposals.awaiting_approval
  end

  def upcoming_conferences
    user.conferences.todo
  end

  def user
    @user ||= User.find(self.user_id)
  end

end

app/models/talk.rb
class Talk

  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :deck_location
  field :archived, :type => Boolean, :default => false

  belongs_to  :user
  has_many  :proposals
  has_many  :abstracts

  def has_details?
    self.deck_location || self.abstracts.first
  end

  def history
    TalkHistory.new(self.id)
  end

  def recently_created?
    self.created_at > Date.today - 2.months
  end

  def recently_updated?
    self.updated_at > Date.today - 1.month
  end

  def submitted?
    self.proposals.present?
  end

  def accepted?
    self.proposals.accepted.present?
  end

  def rejected?
    self.proposals.rejected.present?
  end

  def tags
    tags = []
    tags << "recent"      if recently_created?
    tags << "updated"     if recently_updated?
    tags << "active"      unless self.archived?
    tags << "archived"    if self.archived?
    tags << "unsubmitted" unless self.submitted?
    tags << "submitted"   if self.submitted?
    tags << "accepted"    if self.accepted?
    tags << "rejected"    if self.rejected?
    tags
  end

end

app/models/talk/abstract.rb
class Talk::Abstract

  include Mongoid::Document
  include Mongoid::Timestamps

  field :summary
  field :full_text

  belongs_to :proposal, :class_name => 'Talk::Proposal'
  belongs_to :talk, :class_name => 'Talk::Talk'

  def summary
    self[:summary].present? && self[:summary] || self.full_text.to_s.truncate(200)
  end

end

app/models/talk/proposal.rb
class Talk::Proposal

  include Mongoid::Document
  include Mongoid::Timestamps

  field :submitted_at,      :type => Date
  field :accepted,          :type => Boolean
  field :status_updated_at, :type => Date

  belongs_to :conference, :class_name => 'Conference::Conference'
  belongs_to :talk, :class_name => 'Talk::Talk'
  belongs_to :user
  has_one :bio, :class_name => 'Speaker::Bio'
  has_one :abstract, :class_name => 'Talk::Abstract'

  scope :accepted,  -> { where(:accepted => true) }
  scope :rejected,  -> { where(:accepted => false) }
  scope :submitted, -> { excludes(:submitted_at => nil) }

  def self.awaiting_approval
    submitted.where(:accepted => nil)
  end

  def accepted?
    self.accepted
  end

  def rejected?
    self.accepted.present? && ! self.accepted
  end

  def presented?
    self.conference.end_date < Date.today
  end

end

app/models/talk/talk.rb
class Talk::Talk

  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :deck_location
  field :archived, :type => Boolean, :default => false

  belongs_to  :user
  has_many  :proposals, :class_name => 'Talk::Proposal'
  has_many  :abstracts, :class_name => 'Talk::Abstract'

  def has_details?
    self.deck_location || self.abstracts.first
  end

  def history
    Talk::TalkHistory.new(self.id)
  end

  def recently_created?
    self.created_at > Date.today - 2.months
  end

  def recently_updated?
    self.updated_at > Date.today - 1.month
  end

  def submitted?
    self.proposals.present?
  end

  def accepted?
    self.proposals.accepted.present?
  end

  def rejected?
    self.proposals.rejected.present?
  end

  def tags
    tags = []
    tags << "recent"      if recently_created?
    tags << "updated"     if recently_updated?
    tags << "active"      unless self.archived?
    tags << "archived"    if self.archived?
    tags << "unsubmitted" unless self.submitted?
    tags << "submitted"   if self.submitted?
    tags << "accepted"    if self.accepted?
    tags << "rejected"    if self.rejected?
    tags
  end

end

app/models/talk/talk_history.rb
class Talk::TalkHistory

  attr_reader :talk_id

  def initialize(talk_id)
    @talk_id = talk_id
  end

  def talk
    @talk ||= Talk::Talk.find(self.talk_id)
  end

  def events
    talk_events | proposal_events
  end

  def proposal_events
    events = []
    talk.proposals.each do |proposal|
      events << "#{proposal.created_at.to_s(:concise)}: Proposal submitted to #{proposal.conference.name}"
      events << "#{proposal.status_updated_at.to_s(:concise)}: Talk rejected by #{proposal.conference.name}" if proposal.rejected?
      events << "#{proposal.status_updated_at.to_s(:concise)}: Proposal accepted by #{proposal.conference.name}" if proposal.accepted? && proposal.status_updated_at
      events << "#{proposal.conference.end_date.to_s(:concise)}: Talk given at #{proposal.conference.name}" if proposal.presented?
    end
    events
  end

  def talk_events
    ["#{talk.created_at.to_s(:concise)}: Talk created"]
  end

end

app/controllers/speaker/bios_controller.rb
class Speaker::BiosController < ApplicationController

  include ScopesAndPersistsModel

  before_filter :ensure_current_user
  scopes_and_persists :bio, :class_name => 'Speaker::Bio'

  def index
    @bios = current_user.bios.all
  end

  def new
    @bio = current_user.bios.new
  end

  def edit
  end

  def show
  end

  def destroy
    @bio.destroy && redirect_to(speaker_bios_path(current_user.slug))
  end

  def create
    @bio = current_user.bios.new
    handle_errors_on(:new) || redirect_to(speaker_bios_path(current_user.slug))
  end

  def update
    handle_errors_on(:edit) || redirect_to(speaker_bios_path(current_user.slug))
  end

end

app/controllers/speaker/calendars_controller.rb
class Speaker::CalendarsController < ApplicationController

  before_filter :ensure_current_user

  def show
    redirect_to root_path unless session[:user_id]
    @calendar = Speaker::Calendar.new(current_user)
  end

end

app/controllers/speaker/dashboards_controller.rb
class Speaker::DashboardsController < ApplicationController

  before_filter :ensure_current_user

  def show
    redirect_to root_path unless session[:user_id]
    @dashboard = Speaker::Dashboard.new(:user_id => current_user.id)
  end

end

app/controllers/speaker/talks_controller.rb
class Speaker::TalksController < ApplicationController

  include ScopesAndPersistsModel

  scopes_and_persists :talk, :class_name => "Talk::Talk"

  before_filter :ensure_current_user
  before_filter :scope_abstract, :only => [:new, :edit, :create, :update]

  def index
    @talks = current_user.talks.desc(:created_at)
  end

  def new
    @talk = current_user.talks.new
  end

  def edit
  end

  def show
  end

  def destroy
    @talk.destroy && redirect_to(speaker_talks_path(current_user.slug))
  end

  def create
    @talk = current_user.talks.new
    handle_errors_on(:new)
    @abstract.save! if @abstract.summary.present?
    redirect_to(speaker_talks_path(current_user.slug))
  end

  def update
    handle_errors_on(:edit)
    @abstract.update_attributes(params[:talk_abstract])
    redirect_to(speaker_talks_path(current_user.slug))
  end

  private

  def scope_abstract
    @abstract = @talk.abstracts.first
    @abstract ||= params[:talk_abstract].present? && params[:talk_abstract][:id].present? && @talk.abstracts.where(params[:talk_abstract][:id]).first
    @abstract ||= @talk.abstracts.build(params[:talk_abstract])
  end

end

app/views/speaker/talks/_form.html.haml
.well.form
  = f.hidden_field :user_id, :value => current_user.id
  = fields_for @abstract do |ff|
    = ff.hidden_field :id, :value => @abstract.id
    .span4
      = f.label :title
      = f.text_field :title, :style => 'width: 90%;'
      = f.label :deck_location, "Deck URL"
      = f.text_field :deck_location, :style => 'width: 90%;'
      = ff.label :summary
      = ff.text_area :summary, :style => 'width: 90%; height: 7em;'
    .span6
      = ff.label :full_text, "Full Description"
      = ff.text_area :full_text, :style => 'width: 100%; height: 18em;'

  %br.clear
= f.submit "Save", :class => 'btn btn-primary'
= link_to "Cancel", :back, :class => 'btn'

- if @talk.persisted?
  .pull-right
    = link_to speaker_talk_path(current_user.slug, @talk.id), :method => :delete, :class => 'btn btn-danger', :confirm => 'Are you sure?' do
      %i.icon-trash

app/views/speaker/talks/edit.html.haml
- content_for(:title, @talk.title)

= form_for(@talk, :url => speaker_talk_path(current_user.slug, @talk.id)) do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/speaker/talks/index.html.haml
- content_for(:title, "Your Talks")

- if @talks.count < 2

  .bubble
    %h2
      Speak Up!
    %p
      What are you passionate about? What learning experiences have you had that you would like to share with the world? You certainly have something to share with the world, so what will your next talk be about?
    .left_speech

- if @talks.count > 3
  .btn-group
    %button.btn.inactive
      %i.icon-th
    %button.btn.filter{:data => {:filter => 'mix'}}
      All
    %button.btn.filter{:data => {:filter => 'recent'}}
      Newest
    %button.btn.filter{:data => {:filter => 'updated'}}
      Updated
    %button.btn.filter{:data => {:filter => 'active'}}
      Active
    %button.btn.filter{:data => {:filter => 'archived'}}
      Archived
    %button.btn.filter{:data => {:filter => 'unsubmitted'}}
      Unsubmitted
    %button.btn.filter{:data => {:filter => 'submitted'}}
      Submitted

  %br.clear

#Grid
  .row-fluid{:style => "margin-top: 1em;"}
    %section
      - @talks.each do |talk|
        %div{:class => "#{(['talk', 'mix', 'span4', 'well', 'medium', 'single_spaced'] | talk.tags) * ' '}", :data => {:name => talk.title, :date => talk.updated_at.to_s(:concise)}}
          = formatted_talk(talk, speaker_talk_path(current_user.slug, talk))
          .controls.reveal-on-mouseover
            = link_to speaker_talk_path(current_user.slug, talk), :class => 'btn btn-mini' do
              %i.icon-eye-open
            = link_to edit_speaker_talk_path(current_user.slug, talk), :class => 'btn btn-mini' do
              %i.icon-edit
            = link_to "#", :class => 'btn btn-mini' do
              %i.icon-bullhorn

%br.clear

%a.btn.btn-inverse{:href => "#{new_speaker_talk_path(current_user.slug)}", :style => 'margin-top: 1em;'}
  %i.icon-comment
    %sup +
  Add a Talk


= content_for :javascript do
  $(function(){ $('#Grid').mixitup({showOnLoad: 'mix', sortOnLoad: 'data-name', multiFilter: false, filterLogic: 'and'}); });

app/views/speaker/talks/new.html.haml
- content_for(:title, "Add a Talk")

= form_for(@talk, :url => speaker_talks_path(current_user.slug)) do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/speaker/talks/show.html.haml
- content_for(:title, @talk.title)

.row-fluid
  .span8
    = stat_block('Summary', @talk.abstracts.first && @talk.abstracts.first.summary || "None")
    = stat_block('Abstract', @talk.abstracts.first && @talk.abstracts.first.full_text || "None")
    = stat_block('Uploaded To', link_to(@talk.deck_location, @talk.deck_location)) if @talk.deck_location.present?
    = link_to edit_speaker_talk_path(current_user.slug, @talk.id), :class => 'btn' do
      %i.icon-bullhorn
      Submit This Talk!
    = link_to edit_speaker_talk_path(current_user.slug, @talk.id), :class => 'btn' do
      %i.icon-edit
      Edit
    = link_to "Back", :back, :class => 'btn'

    - if @talk.persisted?
      .pull-right
        = link_to speaker_talk_path(current_user.slug, @talk.id), :method => :delete, :class => 'btn btn-danger', :confirm => 'Are you sure?' do
          %i.icon-trash
  .span4.pull-right
    = stat_block('History', @talk.history.events * "<br />")