config/routes.rb
Sprechen::Application.routes.draw do

  get '/auth/:provider/callback' => "sessions#create"

  get '/sign_out' => "sessions#destroy", :as => 'sign_out'

  resources :topics

  resources :conferences do
    collection do
      resources :search, :only => [:new, :create, :show], :controller => "search"
    end
  end

  namespace :speaker, :path => 'speaker/:user/' do
    resource :calendar
    resource :dashboard
    resources :bios
    resources :talks
  end

  root :to => 'home#index'

end

app/models/dashboard.rb
class Dashboard

  attr_accessor :user_id

  def initialize(args={})
    self.user_id = args[:user_id]
  end

  def accepted_talks
    user.proposals.accepted
  end

  def submitted_talks
    user.proposals.awaiting_approval
  end

  def upcoming_conferences
    user.conferences.todo
  end

  def user
    self.user_id
    @user ||= User.find(self.user_id)
  end

end

app/models/speaker/bio.rb
class Speaker::Bio

  include Mongoid::Document
  include Mongoid::Timestamps

  field :label
  field :content
  field :photo

  belongs_to :user
  belongs_to :proposal, :class_name => 'Talk::Proposal'

end

app/models/speaker/calendar.rb
class Speaker::Calendar

  attr_accessor :subscriber

  def initialize(subscriber)
    self.subscriber = subscriber
  end

  def conferences
    subscriber.conferences.asc(:start_date)
  end

end

app/models/speaker/dashboard.rb
class Speaker::Dashboard

  attr_accessor :user_id

  def initialize(args={})
    self.user_id = args[:user_id]
  end

  def accepted_talks
    user.proposals.accepted
  end

  def submitted_talks
    user.proposals.awaiting_approval
  end

  def upcoming_conferences
    user.conferences.todo
  end

  def user
    @user ||= User.find(self.user_id)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    redirect_to root_path unless session[:user_id]
    @dashboard = Dashboard.new(:user_id => current_user.id)
  end

end

app/controllers/speaker/bios_controller.rb
class Speaker::BiosController < ApplicationController

  include ScopesAndPersistsModel

  before_filter :ensure_current_user
  scopes_and_persists :bio, :class_name => 'Speaker::Bio'

  def index
    @bios = current_user.bios.all
  end

  def new
    @bio = current_user.bios.new
  end

  def edit
  end

  def show
  end

  def destroy
    @bio.destroy && redirect_to(speaker_bios_path(current_user.slug))
  end

  def create
    @bio = current_user.bios.new
    handle_errors_on(:new) || redirect_to(speaker_bios_path(current_user.slug))
  end

  def update
    handle_errors_on(:edit) || redirect_to(speaker_bios_path(current_user.slug))
  end

end

app/controllers/speaker/calendars_controller.rb
class Speaker::CalendarsController < ApplicationController

  before_filter :ensure_current_user

  def show
    redirect_to root_path unless session[:user_id]
    @calendar = Speaker::Calendar.new(current_user)
  end

end

app/controllers/speaker/dashboards_controller.rb
class Speaker::DashboardsController < ApplicationController

  before_filter :ensure_current_user

  def show
    redirect_to root_path unless session[:user_id]
    @dashboard = Speaker::Dashboard.new(:user_id => current_user.id)
  end

end

app/controllers/speaker/talks_controller.rb
class Speaker::TalksController < ApplicationController

  include ScopesAndPersistsModel

  scopes_and_persists :talk, :class_name => "Talk::Talk"

  before_filter :ensure_current_user
  before_filter :scope_abstract, :only => [:new, :edit, :create, :update]

  def index
    @talks = current_user.talks.desc(:created_at)
  end

  def new
    @talk = current_user.talks.new
  end

  def edit
  end

  def show
  end

  def destroy
    @talk.destroy && redirect_to(speaker_talks_path(current_user.slug))
  end

  def create
    @talk = current_user.talks.new
    handle_errors_on(:new)
    @abstract.save! if @abstract.summary.present?
    redirect_to(speaker_talks_path(current_user.slug))
  end

  def update
    handle_errors_on(:edit)
    @abstract.update_attributes(params[:talk_abstract])
    redirect_to(speaker_talks_path(current_user.slug))
  end

  private

  def scope_abstract
    @abstract = @talk.abstracts.first
    @abstract ||= params[:talk_abstract].present? && params[:talk_abstract][:id].present? && @talk.abstracts.where(params[:talk_abstract][:id]).first
    @abstract ||= @talk.abstracts.build(params[:talk_abstract])
  end

end

app/views/speaker/dashboards/_find_conferences.html.haml
.row-fluid
  .span12
    .bubble.closable
      .pull-right.minus-top-margin
        %a.close
          &times;
      %h2
        Choose Your Next Adventure!
      %p
        There are no upcoming conferences on your schedule. Why not
        = link_to 'search for a conference', 'http://lanyrd.com/topics/', :target => '_new'
        and add it to your list?
      .left_speech

app/views/speaker/dashboards/_getting_started.html.haml
.row-fluid
  .span12
    .bubble.closable
      .pull-right.minus-top-margin
        %a.close
          &times;
      %h2
        Let's Get Started!
      %p
        Looks like you're new here, so let me give you a quick overview:
      .indented
        %i{:class => icon_for(current_user, :bios)}
        Create a bio describing how awesome you are.
      .indented
        %i{:class => icon_for(current_user, :talks)}
        Write the abstract for a talk on a topic that you are passionate about.
      .indented
        %i{:class => icon_for(current_user, :conferences)}
        Add a conference and select the talk that you plan on submitting.
      .indented
        %i{:class => icon_for(current_user, :accepted_proposals)}
        When your amazing proposal is accepted, come back here and check it off!
      %p
        There's a lot more that you'll be able to do later, but let's start simple.

      .left_speech

app/views/speaker/dashboards/_submit_something.html.haml
.row-fluid
  .span12
    .bubble.closable
      .pull-right.minus-top-margin
        %a.close
          &times;
      %h2
        What Are You Waiting For?
      %p
        You have at least one conference on your schedule. Why not
        = link_to 'submit on of your talks'
        ?
      .left_speech

app/views/speaker/dashboards/show.html.haml
- content_for(:title, "#{current_user.name}'s Dashboard")

- if current_user.just_getting_started?
  = render 'getting_started'
- elsif @dashboard.upcoming_conferences.empty?
  = render 'find_conferences'
- elsif @dashboard.submitted_talks.empty?
  = render 'submit_something'

.row-fluid
  .span12

    .span4
      %h3.bordered Prospects
      - if @dashboard.upcoming_conferences.empty?
        .well.single_spaced.short
          You have no upcoming conferences with open RFPs.
        %a.btn.btn-inverse.centered{:href => "#{new_conference_path}"}
          %i.icon-calendar
            %sup +
          Add a Conference
      - else
        - @dashboard.upcoming_conferences.each do |conference|
          .well.short.single_spaced
            = formatted_conference(conference).html_safe
            .pull-right
              %i.icon-eye-open
        %a.btn.btn-inverse.centered{:href => "#"}
          %i.icon-calendar
          View Calendar

    .span4
      %h3.bordered Submissions
      - if @dashboard.submitted_talks.empty?
        .well.single_spaced.short
          You have no submitted proposals awaiting approval.
      - @dashboard.submitted_talks.each do |proposal|
        .well.short.single_spaced
          = formatted_proposal(proposal).html_safe
          .pull-right
            %i.icon-eye-open
      %a.btn.btn-inverse{:href => "#"}
        %i.icon-inbox
        View Proposals

    .span4
      %h3.bordered Accepted Talks
      - if @dashboard.accepted_talks.empty?
        .well.single_spaced.short
          You don't have any accepted talks yet.
      - @dashboard.accepted_talks.each do |proposal|
        .well.short.single_spaced
          = formatted_proposal(proposal).html_safe
          .pull-right
            %i.icon-eye-open
      %a.btn.btn-inverse{:href => "#"}
        %i.icon-folder-open
        Review Talks